name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 2.7
          - '3.0'
          - 3.1
          - 3.2
          - 3.3
        rails-version:
          - 5.1
          - 5.2
          - '6.0'
          - 6.1
          - '7.0'
          - 7.1
        exclude:
          - ruby-version: 2.7
            rails-version: 7.1
          - ruby-version: 3.0
            rails-version: 5.1
          - ruby-version: 3.0
            rails-version: 5.2
          - ruby-version: 3.1
            rails-version: 5.1
          - ruby-version: 3.1
            rails-version: 5.2
          - ruby-version: 3.2
            rails-version: 5.1
          - ruby-version: 3.2
            rails-version: 5.2
          - ruby-version: 3.2
            rails-version: 6.0
          - ruby-version: 3.2
            rails-version: 6.1
          - ruby-version: 3.3
            rails-version: 5.1
          - ruby-version: 3.3
            rails-version: 5.2
          - ruby-version: 3.3
            rails-version: 6.0
          - ruby-version: 3.3
            rails-version: 6.1
          - ruby-version: 3.3
            rails-version: 7.0
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails-version }}.gemfile
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          rubygems: 3.0.0
          bundler-cache: true
      - run: bundle exec rake
